#!/bin/bash
#
# internal-functions
#
# Used by bash-my-aws functions to work with stdin and arguments.

# XXX Can we remove __bma_read_inputs and put it into functions to hydrate?
# XXX This would remove issue of whether we can move $@ to first position
#
# local instances=$(echo $@ $(__bma_read_stdin))

# XXX Can we move $@ to first?
__bma_read_inputs() {
  echo $(__bma_read_stdin) $@
}

__bma_read_stdin() {
  [[ -t 0 ]] || awk '{ print $1 }'
}

# Construct a string to be passed to `grep -E`
__bma_read_filters() {
  local IFS_SAVED="$IFS"; IFS=$'|'
  printf -- "$*"
  IFS=$IFS_SAVED
}

__bma_error() {
  echo "ERROR: $@" > /dev/stderr
  return 1
}

__bma_usage() {
  echo "USAGE: ${FUNCNAME[1]} $@" > /dev/stderr
}

## vim: ft=sh
